language:
  ruby

rvm:
  - '2.1'
  - '2.2'
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

  fast_finish:
    true

script:
  rake spec

install:
  gem install --prerelease --development page_rank

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev
